#
# Author: ngoanh2n
#
[versions]
univocity-parsers = "2.9.1"
allure-java       = "2.28.0"
commons           = "1.6.0"
slf4j             = "2.0.10"
junit-jupiter     = "5.10.1"
junit-platform    = "1.10.3"
aspectj           = "1.9.21"
allure-plugin     = "2.11.2"

[libraries]
univocity-parsers       = { group = "com.univocity",       name = "univocity-parsers",       version.ref = "univocity-parsers" }
allure-java-commons     = { group = "io.qameta.allure",    name = "allure-java-commons",     version.ref = "allure-java"       }
commons                 = { group = "com.github.ngoanh2n", name = "commons",                 version.ref = "commons"           }
slf4j-log4j12           = { group = "org.slf4j",           name = "slf4j-log4j12",           version.ref = "slf4j"             }
junit-jupiter-api       = { group = "org.junit.jupiter",   name = "junit-jupiter-api",       version.ref = "junit-jupiter"     }
junit-jupiter-engine    = { group = "org.junit.jupiter",   name = "junit-jupiter-engine",    version.ref = "junit-jupiter"     }
junit-platform-launcher = { group = "org.junit.platform",  name = "junit-platform-launcher", version.ref = "junit-platform"    }
allure-junit5           = { group = "io.qameta.allure",    name = "allure-junit5",           version.ref = "allure-java"       }

[plugins]
allure = { id = "io.qameta.allure", version.ref = "allure-plugin" }
